// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Metadata;

namespace RouteMasterBackend.Models
{
    public partial class RouteMasterContext : DbContext
    {
        public RouteMasterContext()
        {
        }

        public RouteMasterContext(DbContextOptions<RouteMasterContext> options)
            : base(options)
        {
        }

        public virtual DbSet<Accommodation> Accommodations { get; set; }
        public virtual DbSet<AccommodationImage> AccommodationImages { get; set; }
        public virtual DbSet<AccommodationServiceInfo> AccommodationServiceInfos { get; set; }
        public virtual DbSet<AcommodationCategory> AcommodationCategories { get; set; }
        public virtual DbSet<Activity> Activities { get; set; }
        public virtual DbSet<ActivityCategory> ActivityCategories { get; set; }
        public virtual DbSet<ActivityImage> ActivityImages { get; set; }
        public virtual DbSet<ActivityProduct> ActivityProducts { get; set; }
        public virtual DbSet<Administrator> Administrators { get; set; }
        public virtual DbSet<Attraction> Attractions { get; set; }
        public virtual DbSet<AttractionCategory> AttractionCategories { get; set; }
        public virtual DbSet<AttractionClick> AttractionClicks { get; set; }
        public virtual DbSet<AttractionImage> AttractionImages { get; set; }
        public virtual DbSet<AttractionTag> AttractionTags { get; set; }
        public virtual DbSet<Cart> Carts { get; set; }
        public virtual DbSet<CartAccommodationDetail> CartAccommodationDetails { get; set; }
        public virtual DbSet<CartActivitiesDetail> CartActivitiesDetails { get; set; }
        public virtual DbSet<CartExtraServicesDetail> CartExtraServicesDetails { get; set; }
        public virtual DbSet<CommentAccommodationLike> CommentAccommodationLikes { get; set; }
        public virtual DbSet<CommentStatus> CommentStatuses { get; set; }
        public virtual DbSet<CommentsAccommodation> CommentsAccommodations { get; set; }
        public virtual DbSet<CommentsAccommodationImage> CommentsAccommodationImages { get; set; }
        public virtual DbSet<CommentsAttraction> CommentsAttractions { get; set; }
        public virtual DbSet<CommentsAttractionImage> CommentsAttractionImages { get; set; }
        public virtual DbSet<Coupon> Coupons { get; set; }
        public virtual DbSet<ExtraService> ExtraServices { get; set; }
        public virtual DbSet<ExtraServiceImage> ExtraServiceImages { get; set; }
        public virtual DbSet<ExtraServiceProduct> ExtraServiceProducts { get; set; }
        public virtual DbSet<Faq> Faqs { get; set; }
        public virtual DbSet<Faqcategory> Faqcategories { get; set; }
        public virtual DbSet<Member> Members { get; set; }
        public virtual DbSet<MemberImage> MemberImages { get; set; }
        public virtual DbSet<Order> Orders { get; set; }
        public virtual DbSet<OrderAccommodationDetail> OrderAccommodationDetails { get; set; }
        public virtual DbSet<OrderActivitiesDetail> OrderActivitiesDetails { get; set; }
        public virtual DbSet<OrderExtraServicesDetail> OrderExtraServicesDetails { get; set; }
        public virtual DbSet<OrderHandleStatus> OrderHandleStatuses { get; set; }
        public virtual DbSet<PackageCoupon> PackageCoupons { get; set; }
        public virtual DbSet<PackageTour> PackageTours { get; set; }
        public virtual DbSet<Partner> Partners { get; set; }
        public virtual DbSet<PaymentMethod> PaymentMethods { get; set; }
        public virtual DbSet<PaymentStatus> PaymentStatuses { get; set; }
        public virtual DbSet<Permission> Permissions { get; set; }
        public virtual DbSet<Region> Regions { get; set; }
        public virtual DbSet<ReportReason> ReportReasons { get; set; }
        public virtual DbSet<ReportedAttractionComment> ReportedAttractionComments { get; set; }
        public virtual DbSet<Room> Rooms { get; set; }
        public virtual DbSet<RoomImage> RoomImages { get; set; }
        public virtual DbSet<RoomProduct> RoomProducts { get; set; }
        public virtual DbSet<RoomServiceInfo> RoomServiceInfos { get; set; }
        public virtual DbSet<RoomType> RoomTypes { get; set; }
        public virtual DbSet<Schedule> Schedules { get; set; }
        public virtual DbSet<SystemImage> SystemImages { get; set; }
        public virtual DbSet<SystemMessage> SystemMessages { get; set; }
        public virtual DbSet<Town> Towns { get; set; }
        public virtual DbSet<Transportation> Transportations { get; set; }
        public virtual DbSet<TravelPlan> TravelPlans { get; set; }

        protected override void OnModelCreating(ModelBuilder modelBuilder)
        {
            modelBuilder.Entity<Accommodation>(entity =>
            {
                entity.Property(e => e.Address)
                    .IsRequired()
                    .HasMaxLength(300);

                entity.Property(e => e.CreateDate)
                    .HasColumnType("datetime")
                    .HasDefaultValueSql("(getdate())");

                entity.Property(e => e.Description).HasMaxLength(2000);

                entity.Property(e => e.Image).HasMaxLength(200);

                entity.Property(e => e.IndustryEmail).HasMaxLength(255);

                entity.Property(e => e.Name)
                    .IsRequired()
                    .HasMaxLength(30);

                entity.Property(e => e.PhoneNumber).HasMaxLength(20);

                entity.Property(e => e.Website).HasMaxLength(2000);

                entity.HasOne(d => d.AcommodationCategory)
                    .WithMany(p => p.Accommodations)
                    .HasForeignKey(d => d.AcommodationCategoryId)
                    .OnDelete(DeleteBehavior.ClientSetNull)
                    .HasConstraintName("FK__Accommoda__Creat__534D60F1");

                entity.HasOne(d => d.Partner)
                    .WithMany(p => p.Accommodations)
                    .HasForeignKey(d => d.PartnerId)
                    .OnDelete(DeleteBehavior.ClientSetNull)
                    .HasConstraintName("FK__Accommoda__Partn__5441852A");

                entity.HasOne(d => d.Region)
                    .WithMany(p => p.Accommodations)
                    .HasForeignKey(d => d.RegionId)
                    .OnDelete(DeleteBehavior.ClientSetNull)
                    .HasConstraintName("FK__Accommoda__Regio__5535A963");

                entity.HasOne(d => d.Town)
                    .WithMany(p => p.Accommodations)
                    .HasForeignKey(d => d.TownId)
                    .OnDelete(DeleteBehavior.ClientSetNull)
                    .HasConstraintName("FK__Accommoda__TownI__5629CD9C");

                entity.HasMany(d => d.AccommodationServiceInfos)
                    .WithMany(p => p.Accommodations)
                    .UsingEntity<Dictionary<string, object>>(
                        "ServiceInfosAccommodation",
                        l => l.HasOne<AccommodationServiceInfo>().WithMany().HasForeignKey("AccommodationServiceInfoId").OnDelete(DeleteBehavior.ClientSetNull).HasConstraintName("FK__ServiceIn__Accom__6754599E"),
                        r => r.HasOne<Accommodation>().WithMany().HasForeignKey("AccommodationId").OnDelete(DeleteBehavior.ClientSetNull).HasConstraintName("FK__ServiceIn__Accom__66603565"),
                        j =>
                        {
                            j.HasKey("AccommodationId", "AccommodationServiceInfoId").HasName("PK__ServiceI__DE629F1B8F70536B");

                            j.ToTable("ServiceInfos_Accommodations");
                        });
            });

            modelBuilder.Entity<AccommodationImage>(entity =>
            {
                entity.Property(e => e.Image).HasMaxLength(200);

                entity.Property(e => e.Name)
                    .IsRequired()
                    .HasMaxLength(30);

                entity.HasOne(d => d.Accommodation)
                    .WithMany(p => p.AccommodationImages)
                    .HasForeignKey(d => d.AccommodationId)
                    .OnDelete(DeleteBehavior.ClientSetNull)
                    .HasConstraintName("FK__Accommoda__Accom__59063A47");
            });

            modelBuilder.Entity<AccommodationServiceInfo>(entity =>
            {
                entity.Property(e => e.Name)
                    .IsRequired()
                    .HasMaxLength(30);
            });

            modelBuilder.Entity<AcommodationCategory>(entity =>
            {
                entity.Property(e => e.Name)
                    .IsRequired()
                    .HasMaxLength(30);
            });

            modelBuilder.Entity<Activity>(entity =>
            {
                entity.Property(e => e.Description)
                    .IsRequired()
                    .HasMaxLength(2000);

                entity.Property(e => e.Image)
                    .IsRequired()
                    .HasMaxLength(200);

                entity.Property(e => e.Name)
                    .IsRequired()
                    .HasMaxLength(30);

                entity.HasOne(d => d.ActivityCategory)
                    .WithMany(p => p.Activities)
                    .HasForeignKey(d => d.ActivityCategoryId)
                    .OnDelete(DeleteBehavior.ClientSetNull)
                    .HasConstraintName("FK__Activitie__Image__30C33EC3");

                entity.HasOne(d => d.Attraction)
                    .WithMany(p => p.Activities)
                    .HasForeignKey(d => d.AttractionId)
                    .OnDelete(DeleteBehavior.ClientSetNull)
                    .HasConstraintName("FK__Activitie__Attra__32AB8735");

                entity.HasOne(d => d.Region)
                    .WithMany(p => p.Activities)
                    .HasForeignKey(d => d.RegionId)
                    .OnDelete(DeleteBehavior.ClientSetNull)
                    .HasConstraintName("FK__Activitie__Regio__31B762FC");
            });

            modelBuilder.Entity<ActivityCategory>(entity =>
            {
                entity.Property(e => e.Name)
                    .IsRequired()
                    .HasMaxLength(30);
            });

            modelBuilder.Entity<ActivityImage>(entity =>
            {
                entity.Property(e => e.Image)
                    .IsRequired()
                    .HasMaxLength(200);

                entity.HasOne(d => d.Activity)
                    .WithMany(p => p.ActivityImages)
                    .HasForeignKey(d => d.ActivityId)
                    .OnDelete(DeleteBehavior.ClientSetNull)
                    .HasConstraintName("FK__ActivityI__Activ__3864608B");
            });

            modelBuilder.Entity<ActivityProduct>(entity =>
            {
                entity.Property(e => e.Date).HasColumnType("date");

                entity.HasOne(d => d.Activity)
                    .WithMany(p => p.ActivityProducts)
                    .HasForeignKey(d => d.ActivityId)
                    .OnDelete(DeleteBehavior.ClientSetNull)
                    .HasConstraintName("FK__ActivityP__Quant__3587F3E0");
            });

            modelBuilder.Entity<Administrator>(entity =>
            {
                entity.HasIndex(e => e.Email, "UQ__Administ__A9D10534D297649E")
                    .IsUnique();

                entity.Property(e => e.ConfirmCode).HasMaxLength(300);

                entity.Property(e => e.CreateDate)
                    .HasColumnType("datetime")
                    .HasDefaultValueSql("(getdate())");

                entity.Property(e => e.Email)
                    .IsRequired()
                    .HasMaxLength(255);

                entity.Property(e => e.EncryptedPassword)
                    .IsRequired()
                    .HasMaxLength(255);

                entity.Property(e => e.FirstName)
                    .IsRequired()
                    .HasMaxLength(50);

                entity.Property(e => e.LastName)
                    .IsRequired()
                    .HasMaxLength(50);

                entity.HasOne(d => d.Permission)
                    .WithMany(p => p.Administrators)
                    .HasForeignKey(d => d.PermissionId)
                    .OnDelete(DeleteBehavior.ClientSetNull)
                    .HasConstraintName("FK__Administr__Permi__3B75D760");
            });

            modelBuilder.Entity<Attraction>(entity =>
            {
                entity.Property(e => e.Address)
                    .IsRequired()
                    .HasMaxLength(300);

                entity.Property(e => e.Description)
                    .IsRequired()
                    .HasMaxLength(2000);

                entity.Property(e => e.Image).HasMaxLength(200);

                entity.Property(e => e.Name)
                    .IsRequired()
                    .HasMaxLength(30);

                entity.Property(e => e.Website).HasMaxLength(2000);

                entity.HasOne(d => d.AttractionCategory)
                    .WithMany(p => p.Attractions)
                    .HasForeignKey(d => d.AttractionCategoryId)
                    .OnDelete(DeleteBehavior.ClientSetNull)
                    .HasConstraintName("FK__Attractio__Posit__06CD04F7");

                entity.HasOne(d => d.Region)
                    .WithMany(p => p.Attractions)
                    .HasForeignKey(d => d.RegionId)
                    .OnDelete(DeleteBehavior.ClientSetNull)
                    .HasConstraintName("FK__Attractio__Regio__07C12930");

                entity.HasOne(d => d.Town)
                    .WithMany(p => p.Attractions)
                    .HasForeignKey(d => d.TownId)
                    .OnDelete(DeleteBehavior.ClientSetNull)
                    .HasConstraintName("FK__Attractio__TownI__08B54D69");

                entity.HasMany(d => d.Tags)
                    .WithMany(p => p.Attractions)
                    .UsingEntity<Dictionary<string, object>>(
                        "TagsAttraction",
                        l => l.HasOne<AttractionTag>().WithMany().HasForeignKey("TagId").OnDelete(DeleteBehavior.ClientSetNull).HasConstraintName("FK__Tags_Attr__TagId__18EBB532"),
                        r => r.HasOne<Attraction>().WithMany().HasForeignKey("AttractionId").OnDelete(DeleteBehavior.ClientSetNull).HasConstraintName("FK__Tags_Attr__TagId__17F790F9"),
                        j =>
                        {
                            j.HasKey("AttractionId", "TagId").HasName("PK__Tags_Att__0CB582C07733D0F3");

                            j.ToTable("Tags_Attractions");
                        });
            });

            modelBuilder.Entity<AttractionCategory>(entity =>
            {
                entity.Property(e => e.Name)
                    .IsRequired()
                    .HasMaxLength(30);
            });

            modelBuilder.Entity<AttractionClick>(entity =>
            {
                entity.ToTable("AttractionClick");

                entity.Property(e => e.ClickDate)
                    .HasColumnType("datetime")
                    .HasDefaultValueSql("(getdate())");

                entity.HasOne(d => d.Attraction)
                    .WithMany(p => p.AttractionClicks)
                    .HasForeignKey(d => d.AttractionId)
                    .OnDelete(DeleteBehavior.ClientSetNull)
                    .HasConstraintName("FK__Attractio__Click__0C85DE4D");
            });

            modelBuilder.Entity<AttractionImage>(entity =>
            {
                entity.Property(e => e.Image)
                    .IsRequired()
                    .HasMaxLength(200);

                entity.HasOne(d => d.Attraction)
                    .WithMany(p => p.AttractionImages)
                    .HasForeignKey(d => d.AttractionId)
                    .OnDelete(DeleteBehavior.ClientSetNull)
                    .HasConstraintName("FK__Attractio__Attra__1332DBDC");
            });

            modelBuilder.Entity<AttractionTag>(entity =>
            {
                entity.Property(e => e.Name).HasMaxLength(50);
            });

            modelBuilder.Entity<Cart>(entity =>
            {
                entity.HasOne(d => d.Member)
                    .WithMany(p => p.Carts)
                    .HasForeignKey(d => d.MemberId)
                    .OnDelete(DeleteBehavior.ClientSetNull)
                    .HasConstraintName("FK__Carts__MemberId__6AEFE058");
            });

            modelBuilder.Entity<CartAccommodationDetail>(entity =>
            {
                entity.ToTable("Cart_AccommodationDetails");

                entity.HasOne(d => d.Cart)
                    .WithMany(p => p.CartAccommodationDetails)
                    .HasForeignKey(d => d.CartId)
                    .OnDelete(DeleteBehavior.ClientSetNull)
                    .HasConstraintName("FK__Cart_Acco__CartI__756D6ECB");

                entity.HasOne(d => d.RoomProduct)
                    .WithMany(p => p.CartAccommodationDetails)
                    .HasForeignKey(d => d.RoomProductId)
                    .OnDelete(DeleteBehavior.ClientSetNull)
                    .HasConstraintName("FK__Cart_Acco__RoomP__76619304");
            });

            modelBuilder.Entity<CartActivitiesDetail>(entity =>
            {
                entity.ToTable("Cart_ActivitiesDetails");

                entity.HasOne(d => d.ActivityProduct)
                    .WithMany(p => p.CartActivitiesDetails)
                    .HasForeignKey(d => d.ActivityProductId)
                    .OnDelete(DeleteBehavior.ClientSetNull)
                    .HasConstraintName("FK__Cart_Acti__Activ__72910220");

                entity.HasOne(d => d.Cart)
                    .WithMany(p => p.CartActivitiesDetails)
                    .HasForeignKey(d => d.CartId)
                    .OnDelete(DeleteBehavior.ClientSetNull)
                    .HasConstraintName("FK__Cart_Acti__CartI__719CDDE7");
            });

            modelBuilder.Entity<CartExtraServicesDetail>(entity =>
            {
                entity.ToTable("Cart_ExtraServicesDetails");

                entity.HasOne(d => d.Cart)
                    .WithMany(p => p.CartExtraServicesDetails)
                    .HasForeignKey(d => d.CartId)
                    .OnDelete(DeleteBehavior.ClientSetNull)
                    .HasConstraintName("FK__Cart_Extr__CartI__6DCC4D03");

                entity.HasOne(d => d.ExtraServiceProduct)
                    .WithMany(p => p.CartExtraServicesDetails)
                    .HasForeignKey(d => d.ExtraServiceProductId)
                    .OnDelete(DeleteBehavior.ClientSetNull)
                    .HasConstraintName("FK__Cart_Extr__Extra__6EC0713C");
            });

            modelBuilder.Entity<CommentAccommodationLike>(entity =>
            {
                entity.ToTable("Comment_Accommodation_Likes");

                entity.Property(e => e.CommentsAccommodationId).HasColumnName("Comments_AccommodationId");

                entity.Property(e => e.CreateDate)
                    .HasColumnType("datetime")
                    .HasDefaultValueSql("(getdate())");

                entity.HasOne(d => d.CommentsAccommodation)
                    .WithMany(p => p.CommentAccommodationLikes)
                    .HasForeignKey(d => d.CommentsAccommodationId)
                    .OnDelete(DeleteBehavior.ClientSetNull)
                    .HasConstraintName("FK__Comment_A__Comme__02084FDA");

                entity.HasOne(d => d.Member)
                    .WithMany(p => p.CommentAccommodationLikes)
                    .HasForeignKey(d => d.MemberId)
                    .OnDelete(DeleteBehavior.ClientSetNull)
                    .HasConstraintName("FK__Comment_A__Membe__01142BA1");
            });

            modelBuilder.Entity<CommentStatus>(entity =>
            {
                entity.Property(e => e.Name)
                    .IsRequired()
                    .HasMaxLength(50);
            });

            modelBuilder.Entity<CommentsAccommodation>(entity =>
            {
                entity.ToTable("Comments_Accommodations");

                entity.Property(e => e.Cons).HasMaxLength(2000);

                entity.Property(e => e.CreateDate)
                    .HasColumnType("datetime")
                    .HasDefaultValueSql("(getdate())");

                entity.Property(e => e.Pros).HasMaxLength(2000);

                entity.Property(e => e.Reply).HasMaxLength(2000);

                entity.Property(e => e.ReplyAt).HasColumnType("datetime");

                entity.Property(e => e.Title).HasMaxLength(50);

                entity.HasOne(d => d.Accommodation)
                    .WithMany(p => p.CommentsAccommodations)
                    .HasForeignKey(d => d.AccommodationId)
                    .OnDelete(DeleteBehavior.ClientSetNull)
                    .HasConstraintName("FK__Comments___Accom__76969D2E");

                entity.HasOne(d => d.CommentStatus)
                    .WithMany(p => p.CommentsAccommodations)
                    .HasForeignKey(d => d.CommentStatusId)
                    .OnDelete(DeleteBehavior.ClientSetNull)
                    .HasConstraintName("FK__Comments___Comme__778AC167");

                entity.HasOne(d => d.Member)
                    .WithMany(p => p.CommentsAccommodations)
                    .HasForeignKey(d => d.MemberId)
                    .OnDelete(DeleteBehavior.ClientSetNull)
                    .HasConstraintName("FK__Comments___Membe__75A278F5");
            });

            modelBuilder.Entity<CommentsAccommodationImage>(entity =>
            {
                entity.ToTable("Comments_AccommodationImages");

                entity.Property(e => e.CommentsAccommodationId).HasColumnName("Comments_AccommodationId");

                entity.Property(e => e.Image)
                    .IsRequired()
                    .HasMaxLength(200);

                entity.HasOne(d => d.CommentsAccommodation)
                    .WithMany(p => p.CommentsAccommodationImages)
                    .HasForeignKey(d => d.CommentsAccommodationId)
                    .OnDelete(DeleteBehavior.ClientSetNull)
                    .HasConstraintName("FK__Comments___Image__7A672E12");
            });

            modelBuilder.Entity<CommentsAttraction>(entity =>
            {
                entity.ToTable("Comments_Attractions");

                entity.Property(e => e.Content).HasMaxLength(2000);

                entity.Property(e => e.CreateDate)
                    .HasColumnType("datetime")
                    .HasDefaultValueSql("(getdate())");

                entity.HasOne(d => d.Attraction)
                    .WithMany(p => p.CommentsAttractions)
                    .HasForeignKey(d => d.AttractionId)
                    .OnDelete(DeleteBehavior.ClientSetNull)
                    .HasConstraintName("FK__Comments___Attra__1DB06A4F");

                entity.HasOne(d => d.Member)
                    .WithMany(p => p.CommentsAttractions)
                    .HasForeignKey(d => d.MemberId)
                    .OnDelete(DeleteBehavior.ClientSetNull)
                    .HasConstraintName("FK__Comments___Membe__1CBC4616");
            });

            modelBuilder.Entity<CommentsAttractionImage>(entity =>
            {
                entity.ToTable("Comments_AttractionImages");

                entity.Property(e => e.CommentsAttractionId).HasColumnName("Comments_AttractionId");

                entity.Property(e => e.Image)
                    .IsRequired()
                    .HasMaxLength(200);

                entity.HasOne(d => d.CommentsAttraction)
                    .WithMany(p => p.CommentsAttractionImages)
                    .HasForeignKey(d => d.CommentsAttractionId)
                    .OnDelete(DeleteBehavior.ClientSetNull)
                    .HasConstraintName("FK__Comments___Image__208CD6FA");
            });

            modelBuilder.Entity<Coupon>(entity =>
            {
                entity.Property(e => e.EndDate).HasColumnType("datetime");

                entity.Property(e => e.StartDate).HasColumnType("datetime");
            });

            modelBuilder.Entity<ExtraService>(entity =>
            {
                entity.Property(e => e.Description)
                    .IsRequired()
                    .HasMaxLength(2000);

                entity.Property(e => e.Image)
                    .IsRequired()
                    .HasMaxLength(200);

                entity.Property(e => e.Name)
                    .IsRequired()
                    .HasMaxLength(30);

                entity.HasOne(d => d.Attraction)
                    .WithMany(p => p.ExtraServices)
                    .HasForeignKey(d => d.AttractionId)
                    .OnDelete(DeleteBehavior.ClientSetNull)
                    .HasConstraintName("FK__ExtraServ__Attra__3C34F16F");

                entity.HasOne(d => d.Region)
                    .WithMany(p => p.ExtraServices)
                    .HasForeignKey(d => d.RegionId)
                    .OnDelete(DeleteBehavior.ClientSetNull)
                    .HasConstraintName("FK__ExtraServ__Image__3B40CD36");
            });

            modelBuilder.Entity<ExtraServiceImage>(entity =>
            {
                entity.Property(e => e.Image)
                    .IsRequired()
                    .HasMaxLength(200);

                entity.HasOne(d => d.ExtraService)
                    .WithMany(p => p.ExtraServiceImages)
                    .HasForeignKey(d => d.ExtraServiceId)
                    .OnDelete(DeleteBehavior.ClientSetNull)
                    .HasConstraintName("FK__ExtraServ__Extra__41EDCAC5");
            });

            modelBuilder.Entity<ExtraServiceProduct>(entity =>
            {
                entity.Property(e => e.Date).HasColumnType("date");

                entity.HasOne(d => d.ExtraService)
                    .WithMany(p => p.ExtraServiceProducts)
                    .HasForeignKey(d => d.ExtraServiceId)
                    .OnDelete(DeleteBehavior.ClientSetNull)
                    .HasConstraintName("FK__ExtraServ__Quant__3F115E1A");
            });

            modelBuilder.Entity<Faq>(entity =>
            {
                entity.ToTable("FAQs");

                entity.Property(e => e.Answer)
                    .IsRequired()
                    .HasMaxLength(2000);

                entity.Property(e => e.CreateDate)
                    .HasColumnType("datetime")
                    .HasDefaultValueSql("(getdate())");

                entity.Property(e => e.FaqcategoryId).HasColumnName("FAQCategoryId");

                entity.Property(e => e.Image).HasMaxLength(200);

                entity.Property(e => e.ModifiedDate).HasColumnType("datetime");

                entity.Property(e => e.Question)
                    .IsRequired()
                    .HasMaxLength(2000);

                entity.HasOne(d => d.Faqcategory)
                    .WithMany(p => p.Faqs)
                    .HasForeignKey(d => d.FaqcategoryId)
                    .OnDelete(DeleteBehavior.ClientSetNull)
                    .HasConstraintName("FK__FAQs__FAQCategor__2BFE89A6");
            });

            modelBuilder.Entity<Faqcategory>(entity =>
            {
                entity.ToTable("FAQCategories");

                entity.Property(e => e.Name)
                    .IsRequired()
                    .HasMaxLength(30);
            });

            modelBuilder.Entity<Member>(entity =>
            {
                entity.HasIndex(e => e.Email, "UQ__Members__A9D105347A5F4094")
                    .IsUnique();

                entity.HasIndex(e => e.Account, "UQ__Members__B0C3AC4698216BFB")
                    .IsUnique();

                entity.Property(e => e.Account)
                    .IsRequired()
                    .HasMaxLength(30);

                entity.Property(e => e.Address).HasMaxLength(255);

                entity.Property(e => e.Birthday).HasColumnType("datetime");

                entity.Property(e => e.CellPhoneNumber).HasMaxLength(10);

                entity.Property(e => e.ConfirmCode).HasMaxLength(300);

                entity.Property(e => e.CreateDate)
                    .HasColumnType("datetime")
                    .HasDefaultValueSql("(getdate())");

                entity.Property(e => e.Email)
                    .IsRequired()
                    .HasMaxLength(255);

                entity.Property(e => e.EncryptedPassword).HasMaxLength(255);

                entity.Property(e => e.FaceBookAccessCode).HasMaxLength(300);

                entity.Property(e => e.FirstName)
                    .IsRequired()
                    .HasMaxLength(50);

                entity.Property(e => e.GoogleAccessCode).HasMaxLength(300);

                entity.Property(e => e.Image).HasMaxLength(200);

                entity.Property(e => e.LastName)
                    .IsRequired()
                    .HasMaxLength(50);

                entity.Property(e => e.LineAccessCode).HasMaxLength(300);

                entity.Property(e => e.LoginTime).HasColumnType("datetime");
            });

            modelBuilder.Entity<MemberImage>(entity =>
            {
                entity.Property(e => e.Image)
                    .IsRequired()
                    .HasMaxLength(200);

                entity.Property(e => e.Name)
                    .IsRequired()
                    .HasMaxLength(30);

                entity.HasOne(d => d.Member)
                    .WithMany(p => p.MemberImages)
                    .HasForeignKey(d => d.MemberId)
                    .OnDelete(DeleteBehavior.ClientSetNull)
                    .HasConstraintName("FK__MemberIma__Membe__4316F928");
            });

            modelBuilder.Entity<Order>(entity =>
            {
                entity.Property(e => e.CreateDate)
                    .HasColumnType("datetime")
                    .HasDefaultValueSql("(getdate())");

                entity.Property(e => e.ModifiedDate).HasColumnType("datetime");

                entity.HasOne(d => d.Coupons)
                    .WithMany(p => p.Orders)
                    .HasForeignKey(d => d.CouponsId)
                    .OnDelete(DeleteBehavior.ClientSetNull)
                    .HasConstraintName("FK__Orders__CouponsI__0697FACD");

                entity.HasOne(d => d.Member)
                    .WithMany(p => p.Orders)
                    .HasForeignKey(d => d.MemberId)
                    .OnDelete(DeleteBehavior.ClientSetNull)
                    .HasConstraintName("FK__Orders__MemberId__01D345B0");

                entity.HasOne(d => d.OrderHandleStatus)
                    .WithMany(p => p.Orders)
                    .HasForeignKey(d => d.OrderHandleStatusId)
                    .OnDelete(DeleteBehavior.ClientSetNull)
                    .HasConstraintName("FK__Orders__OrderHan__05A3D694");

                entity.HasOne(d => d.PaymentMethod)
                    .WithMany(p => p.Orders)
                    .HasForeignKey(d => d.PaymentMethodId)
                    .OnDelete(DeleteBehavior.ClientSetNull)
                    .HasConstraintName("FK__Orders__PaymentM__03BB8E22");

                entity.HasOne(d => d.PaymentStatus)
                    .WithMany(p => p.Orders)
                    .HasForeignKey(d => d.PaymentStatusId)
                    .OnDelete(DeleteBehavior.ClientSetNull)
                    .HasConstraintName("FK__Orders__PaymentS__04AFB25B");

                entity.HasOne(d => d.TravelPlan)
                    .WithMany(p => p.Orders)
                    .HasForeignKey(d => d.TravelPlanId)
                    .OnDelete(DeleteBehavior.ClientSetNull)
                    .HasConstraintName("FK__Orders__TravelPl__02C769E9");
            });

            modelBuilder.Entity<OrderAccommodationDetail>(entity =>
            {
                entity.Property(e => e.AccommodationName).HasMaxLength(50);

                entity.Property(e => e.CheckIn).HasColumnType("datetime");

                entity.Property(e => e.CheckOut).HasColumnType("datetime");

                entity.Property(e => e.Note).HasMaxLength(2000);

                entity.Property(e => e.RoomName).HasMaxLength(50);

                entity.Property(e => e.RoomType).HasMaxLength(50);

                entity.HasOne(d => d.Accommodation)
                    .WithMany(p => p.OrderAccommodationDetails)
                    .HasForeignKey(d => d.AccommodationId)
                    .OnDelete(DeleteBehavior.ClientSetNull)
                    .HasConstraintName("FK__OrderAcco__Accom__0A688BB1");

                entity.HasOne(d => d.Order)
                    .WithMany(p => p.OrderAccommodationDetails)
                    .HasForeignKey(d => d.OrderId)
                    .OnDelete(DeleteBehavior.ClientSetNull)
                    .HasConstraintName("FK__OrderAcco__Order__09746778");

                entity.HasOne(d => d.RoomProduct)
                    .WithMany(p => p.OrderAccommodationDetails)
                    .HasForeignKey(d => d.RoomProductId)
                    .OnDelete(DeleteBehavior.ClientSetNull)
                    .HasConstraintName("FK__OrderAcco__RoomP__0B5CAFEA");
            });

            modelBuilder.Entity<OrderActivitiesDetail>(entity =>
            {
                entity.Property(e => e.ActivityName)
                    .IsRequired()
                    .HasMaxLength(100);

                entity.Property(e => e.Date).HasColumnType("date");

                entity.HasOne(d => d.Activity)
                    .WithMany(p => p.OrderActivitiesDetails)
                    .HasForeignKey(d => d.ActivityId)
                    .OnDelete(DeleteBehavior.ClientSetNull)
                    .HasConstraintName("FK__OrderActi__Activ__0F2D40CE");

                entity.HasOne(d => d.ActivityProduct)
                    .WithMany(p => p.OrderActivitiesDetails)
                    .HasForeignKey(d => d.ActivityProductId)
                    .OnDelete(DeleteBehavior.ClientSetNull)
                    .HasConstraintName("FK__OrderActi__Activ__10216507");

                entity.HasOne(d => d.Order)
                    .WithMany(p => p.OrderActivitiesDetails)
                    .HasForeignKey(d => d.OrderId)
                    .OnDelete(DeleteBehavior.ClientSetNull)
                    .HasConstraintName("FK__OrderActi__Quant__0E391C95");
            });

            modelBuilder.Entity<OrderExtraServicesDetail>(entity =>
            {
                entity.Property(e => e.Date).HasColumnType("date");

                entity.Property(e => e.ExtraServiceName)
                    .IsRequired()
                    .HasMaxLength(100);

                entity.HasOne(d => d.ExtraService)
                    .WithMany(p => p.OrderExtraServicesDetails)
                    .HasForeignKey(d => d.ExtraServiceId)
                    .OnDelete(DeleteBehavior.ClientSetNull)
                    .HasConstraintName("FK__OrderExtr__Extra__13F1F5EB");

                entity.HasOne(d => d.ExtraServiceProduct)
                    .WithMany(p => p.OrderExtraServicesDetails)
                    .HasForeignKey(d => d.ExtraServiceProductId)
                    .OnDelete(DeleteBehavior.ClientSetNull)
                    .HasConstraintName("FK__OrderExtr__Extra__14E61A24");

                entity.HasOne(d => d.Order)
                    .WithMany(p => p.OrderExtraServicesDetails)
                    .HasForeignKey(d => d.OrderId)
                    .OnDelete(DeleteBehavior.ClientSetNull)
                    .HasConstraintName("FK__OrderExtr__Quant__12FDD1B2");
            });

            modelBuilder.Entity<OrderHandleStatus>(entity =>
            {
                entity.Property(e => e.Name)
                    .IsRequired()
                    .HasMaxLength(30);
            });

            modelBuilder.Entity<PackageTour>(entity =>
            {
                entity.Property(e => e.Description)
                    .IsRequired()
                    .HasMaxLength(2000);

                entity.HasOne(d => d.PackageCoupon)
                    .WithMany(p => p.PackageTours)
                    .HasForeignKey(d => d.PackageCouponId)
                    .OnDelete(DeleteBehavior.ClientSetNull)
                    .HasConstraintName("FK__PackageTo__Packa__46B27FE2");

                entity.HasMany(d => d.Activities)
                    .WithMany(p => p.PackageTours)
                    .UsingEntity<Dictionary<string, object>>(
                        "PackageActivity",
                        l => l.HasOne<Activity>().WithMany().HasForeignKey("ActivityId").OnDelete(DeleteBehavior.ClientSetNull).HasConstraintName("FK__PackageAc__Activ__4E53A1AA"),
                        r => r.HasOne<PackageTour>().WithMany().HasForeignKey("PackageTourId").OnDelete(DeleteBehavior.ClientSetNull).HasConstraintName("FK__PackageAc__Activ__4D5F7D71"),
                        j =>
                        {
                            j.HasKey("PackageTourId", "ActivityId").HasName("PK__PackageA__95FB0D54CF0928EE");

                            j.ToTable("PackageActivities");
                        });

                entity.HasMany(d => d.Attractions)
                    .WithMany(p => p.PackageTours)
                    .UsingEntity<Dictionary<string, object>>(
                        "PackageAttraction",
                        l => l.HasOne<Attraction>().WithMany().HasForeignKey("AttractionId").OnDelete(DeleteBehavior.ClientSetNull).HasConstraintName("FK__PackageAt__Attra__5224328E"),
                        r => r.HasOne<PackageTour>().WithMany().HasForeignKey("PackageTourId").OnDelete(DeleteBehavior.ClientSetNull).HasConstraintName("FK__PackageAt__Attra__51300E55"),
                        j =>
                        {
                            j.HasKey("PackageTourId", "AttractionId").HasName("PK__PackageA__2C0A63F8B327F2F6");

                            j.ToTable("PackageAttractions");
                        });

                entity.HasMany(d => d.ExtraServices)
                    .WithMany(p => p.PackageTours)
                    .UsingEntity<Dictionary<string, object>>(
                        "PackageExtraService",
                        l => l.HasOne<ExtraService>().WithMany().HasForeignKey("ExtraServiceId").OnDelete(DeleteBehavior.ClientSetNull).HasConstraintName("FK__PackageEx__Extra__4A8310C6"),
                        r => r.HasOne<PackageTour>().WithMany().HasForeignKey("PackageTourId").OnDelete(DeleteBehavior.ClientSetNull).HasConstraintName("FK__PackageEx__Extra__498EEC8D"),
                        j =>
                        {
                            j.HasKey("PackageTourId", "ExtraServiceId").HasName("PK__PackageE__0943AA62ADB3D4D1");

                            j.ToTable("PackageExtraServices");
                        });
            });

            modelBuilder.Entity<Partner>(entity =>
            {
                entity.HasIndex(e => e.Email, "UQ__Partners__A9D10534C891EA6F")
                    .IsUnique();

                entity.Property(e => e.ConfirmCode).HasMaxLength(300);

                entity.Property(e => e.CreateDate)
                    .HasColumnType("datetime")
                    .HasDefaultValueSql("(getdate())");

                entity.Property(e => e.Email)
                    .IsRequired()
                    .HasMaxLength(255);

                entity.Property(e => e.EncryptedPassword).HasMaxLength(255);

                entity.Property(e => e.FaceBookAccessCode).HasMaxLength(300);

                entity.Property(e => e.FirstName)
                    .IsRequired()
                    .HasMaxLength(50);

                entity.Property(e => e.GoogleAccessCode).HasMaxLength(300);

                entity.Property(e => e.LastName)
                    .IsRequired()
                    .HasMaxLength(50);

                entity.Property(e => e.LineAccessCode).HasMaxLength(300);

                entity.Property(e => e.LoginTime).HasColumnType("datetime");
            });

            modelBuilder.Entity<PaymentMethod>(entity =>
            {
                entity.Property(e => e.Description)
                    .IsRequired()
                    .HasMaxLength(2000);

                entity.Property(e => e.Name)
                    .IsRequired()
                    .HasMaxLength(30);
            });

            modelBuilder.Entity<PaymentStatus>(entity =>
            {
                entity.Property(e => e.Name)
                    .IsRequired()
                    .HasMaxLength(30);
            });

            modelBuilder.Entity<Permission>(entity =>
            {
                entity.Property(e => e.Name)
                    .IsRequired()
                    .HasMaxLength(30);
            });

            modelBuilder.Entity<Region>(entity =>
            {
                entity.Property(e => e.Name)
                    .IsRequired()
                    .HasMaxLength(30);
            });

            modelBuilder.Entity<ReportReason>(entity =>
            {
                entity.Property(e => e.Reason).HasMaxLength(50);
            });

            modelBuilder.Entity<ReportedAttractionComment>(entity =>
            {
                entity.HasOne(d => d.CommentAttraction)
                    .WithMany(p => p.ReportedAttractionComments)
                    .HasForeignKey(d => d.CommentAttractionId)
                    .OnDelete(DeleteBehavior.ClientSetNull)
                    .HasConstraintName("FK__ReportedA__Comme__25518C17");

                entity.HasOne(d => d.ReportReason)
                    .WithMany(p => p.ReportedAttractionComments)
                    .HasForeignKey(d => d.ReportReasonId)
                    .OnDelete(DeleteBehavior.ClientSetNull)
                    .HasConstraintName("FK__ReportedA__Repor__2645B050");
            });

            modelBuilder.Entity<Room>(entity =>
            {
                entity.Property(e => e.Description).HasMaxLength(2000);

                entity.Property(e => e.Name)
                    .IsRequired()
                    .HasMaxLength(30);

                entity.HasOne(d => d.Accommodation)
                    .WithMany(p => p.Rooms)
                    .HasForeignKey(d => d.AccommodationId)
                    .OnDelete(DeleteBehavior.ClientSetNull)
                    .HasConstraintName("FK__Rooms__Accommoda__5DCAEF64");

                entity.HasOne(d => d.RoomType)
                    .WithMany(p => p.Rooms)
                    .HasForeignKey(d => d.RoomTypeId)
                    .OnDelete(DeleteBehavior.ClientSetNull)
                    .HasConstraintName("FK__Rooms__RoomTypeI__5EBF139D");

                entity.HasMany(d => d.RoomServiceInfos)
                    .WithMany(p => p.Rooms)
                    .UsingEntity<Dictionary<string, object>>(
                        "RoomServiceInfosRoom",
                        l => l.HasOne<RoomServiceInfo>().WithMany().HasForeignKey("RoomServiceInfoId").OnDelete(DeleteBehavior.ClientSetNull).HasConstraintName("FK__RoomServi__RoomS__6D0D32F4"),
                        r => r.HasOne<Room>().WithMany().HasForeignKey("RoomId").OnDelete(DeleteBehavior.ClientSetNull).HasConstraintName("FK__RoomServi__RoomS__6C190EBB"),
                        j =>
                        {
                            j.HasKey("RoomId", "RoomServiceInfoId").HasName("PK__RoomServ__B47A7613CB299AF6");

                            j.ToTable("RoomServiceInfos_Rooms");
                        });
            });

            modelBuilder.Entity<RoomImage>(entity =>
            {
                entity.Property(e => e.Image)
                    .IsRequired()
                    .HasMaxLength(200);

                entity.HasOne(d => d.Room)
                    .WithMany(p => p.RoomImages)
                    .HasForeignKey(d => d.RoomId)
                    .OnDelete(DeleteBehavior.ClientSetNull)
                    .HasConstraintName("FK__RoomImage__Image__619B8048");
            });

            modelBuilder.Entity<RoomProduct>(entity =>
            {
                entity.Property(e => e.Date).HasColumnType("date");

                entity.Property(e => e.NewPrice).HasColumnType("decimal(18, 0)");

                entity.HasOne(d => d.Room)
                    .WithMany(p => p.RoomProducts)
                    .HasForeignKey(d => d.RoomId)
                    .OnDelete(DeleteBehavior.ClientSetNull)
                    .HasConstraintName("FK__RoomProdu__RoomI__6FE99F9F");
            });

            modelBuilder.Entity<RoomServiceInfo>(entity =>
            {
                entity.Property(e => e.Name)
                    .IsRequired()
                    .HasMaxLength(30);
            });

            modelBuilder.Entity<RoomType>(entity =>
            {
                entity.Property(e => e.Name)
                    .IsRequired()
                    .HasMaxLength(30);
            });

            modelBuilder.Entity<Schedule>(entity =>
            {
                entity.Property(e => e.Content)
                    .IsRequired()
                    .HasMaxLength(2000);

                entity.Property(e => e.CreateDate)
                    .HasColumnType("datetime")
                    .HasDefaultValueSql("(getdate())");

                entity.Property(e => e.EndTime).HasColumnType("datetime");

                entity.Property(e => e.StartTime).HasColumnType("datetime");

                entity.HasOne(d => d.Member)
                    .WithMany(p => p.Schedules)
                    .HasForeignKey(d => d.MemberId)
                    .OnDelete(DeleteBehavior.ClientSetNull)
                    .HasConstraintName("FK__Schedules__Membe__65370702");
            });

            modelBuilder.Entity<SystemImage>(entity =>
            {
                entity.Property(e => e.Image)
                    .IsRequired()
                    .HasMaxLength(200);
            });

            modelBuilder.Entity<SystemMessage>(entity =>
            {
                entity.Property(e => e.Content)
                    .IsRequired()
                    .HasMaxLength(2000);

                entity.HasOne(d => d.Member)
                    .WithMany(p => p.SystemMessages)
                    .HasForeignKey(d => d.MemberId)
                    .OnDelete(DeleteBehavior.ClientSetNull)
                    .HasConstraintName("FK__SystemMes__Membe__7D439ABD");
            });

            modelBuilder.Entity<Town>(entity =>
            {
                entity.Property(e => e.Name)
                    .IsRequired()
                    .HasMaxLength(30);

                entity.HasOne(d => d.Region)
                    .WithMany(p => p.Towns)
                    .HasForeignKey(d => d.RegionId)
                    .OnDelete(DeleteBehavior.ClientSetNull)
                    .HasConstraintName("FK__Towns__Name__4D94879B");
            });

            modelBuilder.Entity<Transportation>(entity =>
            {
                entity.ToTable("Transportation");

                entity.Property(e => e.Arrival)
                    .IsRequired()
                    .HasMaxLength(200);

                entity.Property(e => e.Departure)
                    .IsRequired()
                    .HasMaxLength(200);

                entity.Property(e => e.Vehicle)
                    .IsRequired()
                    .HasMaxLength(50);

                entity.HasOne(d => d.TravelPlan)
                    .WithMany(p => p.Transportations)
                    .HasForeignKey(d => d.TravelPlanId)
                    .OnDelete(DeleteBehavior.ClientSetNull)
                    .HasConstraintName("FK__Transport__Trave__681373AD");
            });

            modelBuilder.Entity<TravelPlan>(entity =>
            {
                entity.Property(e => e.CreateDate)
                    .HasColumnType("datetime")
                    .HasDefaultValueSql("(getdate())");

                entity.HasOne(d => d.Member)
                    .WithMany(p => p.TravelPlans)
                    .HasForeignKey(d => d.MemberId)
                    .OnDelete(DeleteBehavior.ClientSetNull)
                    .HasConstraintName("FK__TravelPla__Membe__55F4C372");

                entity.HasMany(d => d.ActivityProducts)
                    .WithMany(p => p.TravelPlans)
                    .UsingEntity<Dictionary<string, object>>(
                        "PlanActivity",
                        l => l.HasOne<ActivityProduct>().WithMany().HasForeignKey("ActivityProductId").OnDelete(DeleteBehavior.ClientSetNull).HasConstraintName("FK__PlanActiv__Activ__5D95E53A"),
                        r => r.HasOne<TravelPlan>().WithMany().HasForeignKey("TravelPlanId").OnDelete(DeleteBehavior.ClientSetNull).HasConstraintName("FK__PlanActiv__Activ__5CA1C101"),
                        j =>
                        {
                            j.HasKey("TravelPlanId", "ActivityProductId").HasName("PK__PlanActi__EB02F9A0E2C1D979");

                            j.ToTable("PlanActivities");
                        });

                entity.HasMany(d => d.Attractions)
                    .WithMany(p => p.TravelPlans)
                    .UsingEntity<Dictionary<string, object>>(
                        "PlanAttraction",
                        l => l.HasOne<Attraction>().WithMany().HasForeignKey("AttractionId").OnDelete(DeleteBehavior.ClientSetNull).HasConstraintName("FK__PlanAttra__Attra__6166761E"),
                        r => r.HasOne<TravelPlan>().WithMany().HasForeignKey("TravelPlanId").OnDelete(DeleteBehavior.ClientSetNull).HasConstraintName("FK__PlanAttra__Attra__607251E5"),
                        j =>
                        {
                            j.HasKey("TravelPlanId", "AttractionId").HasName("PK__PlanAttr__99DDD1EE7051FFC4");

                            j.ToTable("PlanAttractions");
                        });

                entity.HasMany(d => d.ExtraServiceProducts)
                    .WithMany(p => p.TravelPlans)
                    .UsingEntity<Dictionary<string, object>>(
                        "PlanExtraService",
                        l => l.HasOne<ExtraServiceProduct>().WithMany().HasForeignKey("ExtraServiceProductId").OnDelete(DeleteBehavior.ClientSetNull).HasConstraintName("FK__PlanExtra__Extra__59C55456"),
                        r => r.HasOne<TravelPlan>().WithMany().HasForeignKey("TravelPlanId").OnDelete(DeleteBehavior.ClientSetNull).HasConstraintName("FK__PlanExtra__Extra__58D1301D"),
                        j =>
                        {
                            j.HasKey("TravelPlanId", "ExtraServiceProductId").HasName("PK__PlanExtr__4FFE2B651A05B20D");

                            j.ToTable("PlanExtraServices");
                        });
            });

            OnModelCreatingPartial(modelBuilder);
        }

        partial void OnModelCreatingPartial(ModelBuilder modelBuilder);
    }
}